### ISSUE TITLE
zadanie 2

### ISSUE THREAD

**Issue by arkadiusoo** [arkadiuso000/numerki2024#3]
Do realizacji tego zadania musimy podjąć następujące akcje:
 - [x] obmyślić sposób zapisu macierzy równań do pliku (czy wszystko w ładujemy do jednego pliku czy każde osobno)
 - [x] funkcja wczytywania z pliku
 - [x] funkcja wyznaczania poszczególnych x - tutaj chodzi o to, że dla każdego row z x przerzucamy wszystkie inne na drugą stronę i dzielimy przez to co stoi przy x po lewej stronie (zdjecie dla podgladu o co chodzi)
![IMG_8024](https://github.com/arkadiuso000/numerki2024/assets/139708308/4b3bb718-c8e7-493f-9e57-3655ef2825b7)

- [x] funkcja podstawiania i rozwiązywania takiego równania

Reopen:
- [x] metoda do przeksztalcania macierzy do diagonalnej dominujacej
- [x] zabezpieczyc program przed nieskonczona petla -> jezeli precyzja rosnie zwroc false oraz  poprzedne wyliczenie
- [x] dodac dodatkowa metode sprawdzania dokladnosci
- [x] zweryfikowac output w mainie

**Comment by Ayyker** [comment]
TPW bawi i uczy

**Comment by arkadiusoo** [comment]
z technicznego punktu widzenia zadanie jest zrobione, zostaje tylko wykonac sprawozdanie
